export const pizzaData = [
  {
    id: 1,
    name: "Margherita",
    description: "Salsa de tomate, mozzarella fresca y albahaca",
    price: 10.99,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 2,
    name: "Pepperoni",
    description: "Salsa de tomate, mozzarella y pepperoni",
    price: 12.99,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 3,
    name: "Hawaiana",
    description: "Salsa de tomate, mozzarella, jamón y piña",
    price: 13.99,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 4,
    name: "Cuatro Quesos",
    description: "Mozzarella, gorgonzola, parmesano y queso de cabra",
    price: 14.99,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 5,
    name: "Vegetariana",
    description: "Salsa de tomate, mozzarella, pimientos, cebolla, champiñones y aceitunas",
    price: 13.99,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 6,
    name: "BBQ Chicken",
    description: "Salsa BBQ, mozzarella, pollo, cebolla roja y cilantro",
    price: 15.99,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 7,
    name: "Mexicana",
    description: "Salsa de tomate, mozzarella, jalapeños, carne molida y nachos",
    price: 15.99,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 8,
    name: "Suprema",
    description: "Salsa de tomate, mozzarella, pepperoni, salchicha, pimientos, cebolla y champiñones",
    price: 16.99,
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 9,
    name: "Carbonara",
    description: "Crema, mozzarella, panceta, huevo y parmesano",
    price: 14.99,
    image: "/placeholder.svg?height=400&width=600",
  },
]
